name: tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
          - "windows-latest"
        php:
          - 8.1
          - 8.2
          - 8.3
          - 8.4
        laravel:
          - "11.x"
          - "10.x"
        dependencies:
          - "highest"
          - "lowest"
        experimental:
          - false
        exclude:
          - php: 8.1
            laravel: "11.x"
          - php: 8.4
            laravel: "10.x"

    name: Laravel:${{ matrix.laravel }} / PHP:${{ matrix.php }} / OS:${{ matrix.os }} ${{ matrix.dependencies == 'highest' && '⬆️' || '⬇️' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, intl, fileinfo
          coverage: none

      - name: Install dependencies
        uses: "ramsey/composer-install@v3"
        with:
          composer-options: "--prefer-dist --no-cache --with=illuminate/collections:${{ matrix.laravel }}"

      - name: Execute tests
        run: vendor/bin/phpunit
